model:
  exp_class_distance: 4
  regularization_ratio: 0.0000001
  batch_handling: "pair_margin_miner"
  bh_kwargs:
    pos_neg_ratio: null
  resnet_config:
    first_conv:
      in_channels: 3
      out_channels: 64
      kernel_size: 5
      stride: 2
      padding: 3
    block_list: [
      {
        in_channels: 64,
        out_channels: 64,
        kernel_size: 3,
        stride: 1,
        padding: "same",
      },
      {
        in_channels: 64,
        out_channels: 128,
        kernel_size: 3,
        stride: 2,
        padding: 1,
      },
      {
        in_channels: 128,
        out_channels: 128,
        kernel_size: 3,
        stride: 1,
        padding: "same",
      },
      {
        in_channels: 128,
        out_channels: 256,
        kernel_size: 3,
        stride: 2,
        padding: 1,
      },
      {
        in_channels: 256,
        out_channels: 256,
        kernel_size: 3,
        stride: 1,
        padding: "same",
      },
      {
        in_channels: 256,
        out_channels: 512,
        kernel_size: 3,
        stride: 2,
        padding: 1,
      },
    ]
    pool_size: 2
  mlp_config:
    block_list: [
      {
        in_size: 2048,
        out_size: 1024,
        activation_fun: "relu",
        batch_norm: True,
        dropout: 0.0
      },
      {
        in_size: 1024,
        out_size: 256,
        activation_fun: "none",
        batch_norm: False,
        dropout: 0.0
      },
    ]
  lr: 1.0e-3
  img_key: 0
  class_key: 1
  precision_k: [2]
  recall_k: [1, 2]